### ISSUE TITLE
AlternativeTo.net is a great crowdsourced website. It's news archive is a good list in my opinion.

### ISSUE THREAD

**Issue by Ornataweaver** [elegantmonkeys/daily#8]
check https://alternativeto.net/news/all.
I don't understand why this site is not as famous as it should be! It has been really useful to me.
Tell me what you think about the website.
Tell me what you think about the news archive.

Thank you for your time.

**Comment by idoshamun** [comment]
Thanks for the suggestion, I will take a look and see if it fits Daily's content :)

**Comment by Ornataweaver** [comment]
I'll be happy to hear your opinion about the site itself, and it's presence on daily.

**Comment by idoshamun** [comment]
@Ornataweaver I went through the website and I think it is more of technology news kind of website and not development as we currently focused on. This might be relevant for the far future.
Anyway, thanks for the suggestion and I look forward for more. In addition, stay tuned because today we have an announcement.
